### ISSUE TITLE
Icon color for light/dark theme

### ISSUE THREAD

**Issue by LisaJackson24-2** [Wielding/Windicator#1]
![2023-02-22_17-32](https://user-images.githubusercontent.com/125877645/220672646-08aa882a-a2d3-46c0-8793-2079e26889cb.png)

In my opinion, if you do not make an automatic/manual change of the icon, then you should use some minimalistic color, preferably close to the standard system color (I took more blue), although it will not be as minimalistic as white/black, but it will look good in the light and darker topics.

If you decide to use it, I attach the icons below (png and ico).

For those who like this version of the icons, I am attaching the assembled finished program below (I did not make any changes, only replaced the icons).

<< The link to the executable has been removed by Wielding >>

[Windicator Icons.zip](https://github.com/Wielding/Windicator/files/10805550/Windicator.Icons.zip)

**Comment by Wielding** [comment]
Thank you very much for your input.   Your icons are much nicer than mine, and I will consider at minimum replacing mine with yours. I created them quickly, and they look good on my system.  I am more of a function over form person.  Plus, I did not really expect anyone else to use it.  I have no idea when I might look into this, since I have since moved to using Linux full-time. I rarely use my Windows machine anymore. 

Furthermore, I would recommend you consider forking the project and adding your icons there instead of supplying an executable in your issue. I would even consider accepting a pull request for the changes, and I could create a new release and supply a newer executable myself.  I will be deleting this issue because of the potential security implications of an executable referenced in my repositories that was not created by me without being able to verify the source code that created it.  Maybe I am being overcautious.  These days, you can't be too careful downloading things like this.  I have no reason to believe that it is malicious.  I also have no reason to believe it is not.  You are welcome to reply to me here with any concerns about my concerns.  If I don't hear back from you soon, I will delete this issue unless you can edit the original issue without the attached executable.  I am not even sure it is possible to edit your original issue.   If you can't, kindly let me know, and I will delete the issue and you can recreate it without the attached executable.  I have already downloaded the icons.

Thanks again.

**Comment by Wielding** [comment]
It seems I was able to remove the link to the executable from your original post, so I learned something today.  I will leave this issue active.

**Comment by LisaJackson24-2** [comment]
> Thank you very much for your input. Your icons are much nicer than mine, and I will consider at minimum replacing mine with yours. I created them quickly, and they look good on my system. I am more of a function over form person. Plus, I did not really expect anyone else to use it. I have no idea when I might look into this, since I have since moved to using Linux full-time. I rarely use my Windows machine anymore.
> 
> Furthermore, I would recommend you consider forking the project and adding your icons there instead of supplying an executable in your issue. I would even consider accepting a pull request for the changes, and I could create a new release and supply a newer executable myself. I will be deleting this issue because of the potential security implications of an executable referenced in my repositories that was not created by me without being able to verify the source code that created it. Maybe I am being overcautious. These days, you can't be too careful downloading things like this. I have no reason to believe that it is malicious. I also have no reason to believe it is not. You are welcome to reply to me here with any concerns about my concerns. If I don't hear back from you soon, I will delete this issue unless you can edit the original issue without the attached executable. I am not even sure it is possible to edit your original issue. If you can't, kindly let me know, and I will delete the issue and you can recreate it without the attached executable. I have already downloaded the icons.
> 
> Thanks again.

Well, I branched the project. But apart from replacing some icons with others, I didn't do anything 😀, moreover, I didn't know if you would like such icons, so I decided to contact you through the issue first. It would be possible to attach a link to some resource (for example dropbox), maybe this is a better option than throwing the archive directly into the issue. It's just that if I was looking for a Virtual Desktop Indicator, and I would like to get it with these icons, I would like that there is already a ready-made executable file, because many people publish the source code, which is absolutely useless for the average user.
But if you could possibly accept the change request and build a newer executable yourself, that would be great. I've been using your program with the original icons for about a week, and they are in principle very ok in a dark theme, but when switching to a light theme, they are somewhat conspicuous and the overly white frame causes some visual discomfort.
Therefore, today I decided to replace them with neutral light blue ones (which somewhat resemble the notification icon in the standard color of Windows 11), so that the program looks good in both theme variants and does not stand out from the overall design of the system.
And in general, I was looking for an application after the reverse transition, unlike you, from Linux to Windows 😅
And I am very grateful to you for a wonderful application 😉

**Comment by Wielding** [comment]
I do like the icons. I will see about getting my development environment up and running when I get a chance.  I have been putting it off since I have not had any reason to have it working lately.  Until now.  I might just add a command line option to switch between icons since I don't want to add any persistent storage to remember configuration options.

**Comment by LisaJackson24-2** [comment]
> I do like the icons. I will see about getting my development environment up and running when I get a chance. I have been putting it off since I have not had any reason to have it working lately. Until now. I might just add a command line option to switch between icons since I don't want to add any persistent storage to remember configuration options.

In my opinion, a simpler option for the average user, if you want to keep the current version of the icons, would be the option to split them into two separate releases: Windicator Version 1.1.5 Classic and Windicator Version 1.1.5 Modern (the names may be completely else, this just as an example, and the version, respectively, I also took the most recent one just for an example). Then the user can easily choose the desired option. Well, it's just a suggestion, of course it's up to you.

I also put the exe file (more precisely, the exe, which is packed in a zip) in my repository, referring note that I only replaced the icons and the whole project is yours. I'm attaching the link here if you don't mind if someone visits this issue, can see the link.

https://github.com/LisaJackson24-2/Windicator/releases/tag/1.1.5

**Comment by LisaJackson24-2** [comment]
> > I do like the icons. I will see about getting my development environment up and running when I get a chance. I have been putting it off since I have not had any reason to have it working lately. Until now. I might just add a command line option to switch between icons since I don't want to add any persistent storage to remember configuration options.
> 
> In my opinion, a simpler option for the average user, if you want to keep the current version of the icons, would be the option to split them into two separate releases: Windicator Version 1.1.5 Classic and Windicator Version 1.1.5 Modern (the names may be completely else, this just as an example, and the version, respectively, I also took the most recent one just for an example). Then the user can easily choose the desired option. Well, it's just a suggestion, of course it's up to you.
> 
> I also put the exe file (more precisely, the exe, which is packed in a zip) in my repository, referring note that I only replaced the icons and the whole project is yours. I'm attaching the link here if you don't mind if someone visits this issue, can see the link.
> 
> https://github.com/LisaJackson24-2/Windicator/releases/tag/1.1.5

Here I mean not renaming the program as such, but simply changing the file name itself when publishing to simply distinguish between them.

**Comment by LisaJackson24-2** [comment]
> I do like the icons. I will see about getting my development environment up and running when I get a chance. I have been putting it off since I have not had any reason to have it working lately. Until now. I might just add a command line option to switch between icons since I don't want to add any persistent storage to remember configuration options.

And if you already plan to introduce improvements, add a command line parameter to switch between icons, etc., then I would abandon the data of my icons, and use something classic, like the ones I attached for the light and dark version, so that it looks as if it is systemic. I made this version with blue icons just so that they look good in both versions of the theme, since in your program there is only one version of icons, and I did not want to manually switch between two exe files for the light/dark version.

[Minimalist Dark-Light Icons.zip](https://github.com/Wielding/Windicator/files/10807612/Minimalist.Dark-Light.Icons.zip)

**Comment by LisaJackson24-2** [comment]
> I do like the icons. I will see about getting my development environment up and running when I get a chance. I have been putting it off since I have not had any reason to have it working lately. Until now. I might just add a command line option to switch between icons since I don't want to add any persistent storage to remember configuration options.

And if you already plan to introduce improvements, add a command line parameter to switch between icons, etc., then I would abandon the data of my icons, and use something classic, like the ones I attached for the light and dark version, so that it looks as if it is systemic. I made this version with blue icons just so that they look good in both versions of the theme, since in your program there is only one version of icons, and I did not want to manually switch between two exe files for the light/dark version.

![1](https://user-images.githubusercontent.com/125877645/220737896-f4b486b3-ef15-45f0-bacc-d26342747d93.png)

[Minimalist Dark-Light Icons.zip](https://github.com/Wielding/Windicator/files/10807620/Minimalist.Dark-Light.Icons.zip)

**Comment by Wielding** [comment]
Maybe I will look into the ability to detect theme changes.  If I can do that without much trouble, I can automatically swap icon sets when switching between dark/light.  I am just against having any sort of config file or registry entries for something this basic.  A majority of my apps, most of them not on github, don't require configuration or registry entries and are completely portable.  I like to keep it simple.

**Comment by LisaJackson24-2** [comment]
> Maybe I will look into the ability to detect theme changes. If I can do that without much trouble, I can automatically swap icon sets when switching between dark/light. I am just against having any sort of config file or registry entries for something this basic. A majority of my apps, most of them not on github, don't require configuration or registry entries and are completely portable. I like to keep it simple.

That's why I made a blue version of the icons, so as not to complicate anything, because the possibility of choosing between different sets of icons, or automatically switching to a dark/light theme version, most likely will not be implemented, at least that's what says in the README of your repository. And that is why I offered an additional option with a different set of icons, which does not affect the program code in any way. It will just be necessary to assemble your version by simply replacing the icons and naming the exe file a different name. Then you will have two different options in the repository, which are not related to each other in any way, the user will be able to look and choose a more suitable option for himself.

And if you already make changes to the code, I don't see any sense in this, since you don't really need this program anymore, because you use Linux, then you should already implement it with a classic version of icons that will look elegant in the system.

I just didn't know if the project was somehow alive. Because many do not make any changes for years after publication, do not respond to issue. That's why I first published the exe file, so that if someone was looking for a similar program, he could get it in this version.

In the end. The most ideal option in my opinion, if you are satisfied with my set of blue icons, the parallel existence of two versions of programs, just with different icons. That is, you just need to set aside 10-15 minutes to simply assemble the program with this set of icons and put it in your storage. Probably, it will be possible to implement in a short time, just by finding free time. And if you have a desire to modernize something in the future, you will implement it. But this will clearly not happen in the near future. And from my experience, many projects are abandoned and maximally supported at the level of eliminating critical bugs. Therefore, such an option with two parallel existences does not require any effort, just a few minutes of your free time 🙃

**Comment by LisaJackson24-2** [comment]
> Maybe I will look into the ability to detect theme changes. If I can do that without much trouble, I can automatically swap icon sets when switching between dark/light. I am just against having any sort of config file or registry entries for something this basic. A majority of my apps, most of them not on github, don't require configuration or registry entries and are completely portable. I like to keep it simple.

That's why I made a blue version of the icons, so as not to complicate anything, because the possibility of choosing between different sets of icons, or automatically switching to a dark/light theme version, most likely will not be implemented, at least that's what says in the README of your repository. And that is why I offered an additional option with a different set of icons, which does not affect the program code in any way. It will just be necessary to assemble your version by simply replacing the icons and naming the exe file a different name. Then you will have two different options in the repository, which are not related to each other in any way, the user will be able to look and choose a more suitable option for himself.

And if you already make changes to the code, I don't see any sense in this, since you don't really need this program anymore, because you use Linux, then you should already implement it with a classic version of icons that will look elegant in the system.

I just didn't know if the project was somehow alive. Because many do not make any changes for years after publication, do not respond to issue. That's why I first published the exe file, so that if someone was looking for a similar program, he could get it in this version.

In the end. The most ideal option in my opinion, if you are satisfied with my set of blue icons, the parallel existence of two versions of programs, just with different icons. That is, you just need to set aside 10-15 minutes to simply assemble the program with this set of icons and put it in your GitHub storage. Probably, it will be possible to implement in a short time, just by finding free time. And if you have a desire to modernize something in the future, you will implement it. But this will clearly not happen in the near future. And from my experience, many projects are abandoned and maximally supported at the level of eliminating critical bugs. Therefore, such an option with two parallel existences does not require any effort, just a few minutes of your free time 🙃

And of course, it is desirable to post a screenshot in README so that people can see which icons are used in which version.

**Comment by Wielding** [comment]
I think I am going to investigate auto switching.  I have identified some possible methods for implementing it.  I still use my Windows machine occasionally, and the roadmap only says "Not Likely" due to the fact that I really did not expect anybody to use it, and I was satisfied with the functionality as-is for myself.  When I have a chance I would be happy to implement some enhancements since there is interest.   I just have to roll-up my sleeves and install my development tools on my Windows workstation since I wiped it clean a little while back and only installed some Adobe stuff that I can't run on Linux on it since then.

**Comment by Wielding** [comment]
Long time huh?  My Windows machine bit the dust and I was too busy to bother with buying a new machine and set it up.  I finally just installed a Windows VM under linux and used that to add the code for your blue icons.  There is an icons branch now that I will eventually move into main and cut a release.  If you just add a command line option **--blue** when running the executable it will use your icons instead of my original ones.  I am going to try and make some dark icons as well before I generate an executable.  Are you able to build it, or did you just edit the internal resources to create your version?

**Comment by Wielding** [comment]
I have added your blue icons and new dark icons.  The binary has been published as release 1.2.0.

**Comment by LisaJackson24-2** [comment]
> Long time huh? My Windows machine bit the dust and I was too busy to bother with buying a new machine and set it up. I finally just installed a Windows VM under linux and used that to add the code for your blue icons. There is an icons branch now that I will eventually move into main and cut a release. If you just add a command line option **--blue** when running the executable it will use your icons instead of my original ones. I am going to try and make some dark icons as well before I generate an executable. Are you able to build it, or did you just edit the internal resources to create your version?

Yup, almost six months have passed already 😜
THX for finding the time and releasing a new version, but there is a little issue. In the blue-colored icons, if you go beyond the 10th workspace (represented by "0"), I used the "hash#" symbol, which, in my opinion, is a more logical way to indicate the number and is widely used elsewhere. However, you used "asterisk*". As a result, I also renamed the icon itself from "asterisk*" to "hash#". So now, in the version you released, instead of the icon, an empty space is displayed because the file with the name "asterisk*" was not found in the blue icon pack.

Also, in my opinion, it would be preferable to bring the icons to a unified standard, and using the symbol "hash#" is still more logical than "asterisk*".

P.S. In general, I would suggest paying attention to the use of light/dark variants of icons used in this project (or similar):
https://github.com/esvres/vdn/tree/main/src/VirtualDesktopNumber/Assets/Icons
They look like a system feature because the icons are very similar in style to those used by Microsoft itself. In that case, even the blue icon pack I suggested will become unnecessary.

![1](https://github.com/Wielding/Windicator/assets/125877645/ba0d1995-57de-4d98-83a2-b80e72406b1c)

**Comment by Wielding** [comment]
I originally tried the hash sign but it did not look as nice in the circular icon, however, you are correct that it makes more sense.  The asterisk looked better and I never have more that 4 virtual desktops so I don't ever see it anyway.   I don't care for the icons in the project you referenced.  The rounded square just does not do it for me so if anything they would have to be an addition, not a replacement since I like my round icons.  I can add new icon sets very easily.   Any possible changes will have to wait until I get a new Windows machine which has become more of a priority since I have a need to dust off some old Adobe Indesign projects coming up.  Using the VM to do this is not great.
